# Markdown extensions — math stash/expand around the Markdown pass.
#
# One file per `# --- X ---` pass of the pre/post-processing pipeline; the
# pass ORDER is fixed in ../markdown_extensions.cr (`preprocess` /
# `postprocess`). Parts only reopen the module: no requires, no load-time
# statements (scripts/check_no_toplevel_effects.sh).
module Hwaro
  module Content
    module Processors
      module MarkdownExtensions
        # --- Math ---
        DISPLAY_MATH_RE = InlineMarkdown::DISPLAY_MATH_RE
        INLINE_MATH_RE  = InlineMarkdown::INLINE_MATH_RE
        # Code-span pattern confined to one line, for stashing inside
        # multi-line chunks: a stray lone backtick in one paragraph must not
        # absorb text from another.
        SINGLE_LINE_CODE_SPAN_RE = /`[^`\n]+`/
        # CommonMark `<scheme:…>` autolink: its text is a URL, not prose.
        AUTOLINK_RE = /<[A-Za-z][A-Za-z0-9+.\-]{1,31}:[^\s<>]*>/
        # Inline `<code>…</code>` HTML spans — generated by InlineMarkdown
        # for table cells / definition bodies (where the original backticks
        # are already consumed), or author-written raw HTML. Their content
        # is code: the strikethrough/footnote/math passes must treat it as
        # opaque, exactly like backtick spans. `[^<]*` keeps the match to a
        # flat element (generated spans never contain tags); the attribute
        # scan is quote-aware so a `>` inside a quoted value doesn't end
        # the opening tag early.
        HTML_CODE_SPAN_RE = /<code(?:\s(?:[^>"']|"[^"]*"|'[^']*')*)?>[^<]*<\/code>/

        # Placeholder emitted by transform_outside_code_spans for a stashed
        # code span; the capture is the span's index.
        CODE_SPAN_TOKEN_RE = /\x00CS(\d{1,9})\x00/
        # CommonMark "type 6" HTML-block start condition (common block tags,
        # including the <table>/<dl>/<div> markup hwaro itself generates).
        # A line opening one of these starts a raw-HTML block that runs to
        # the next blank line — Markd performs NO inline parsing there, so
        # backslash escapes ship verbatim instead of collapsing.
        HTML_BLOCK_START_RE = /^ {0,3}<\/?(?:address|article|aside|blockquote|caption|center|col|colgroup|dd|details|dialog|div|dl|dt|fieldset|figcaption|figure|footer|form|h[1-6]|header|hr|li|main|menu|nav|ol|p|section|summary|table|tbody|td|tfoot|th|thead|tr|ul)(?:[\s>\/]|\r?$)/i

        # A math span captured by `stash_math`, awaiting `expand_math`.
        # `source` is the span as written (delimiters included), for
        # `protect_math`.
        record MathSpan, display : Bool, body : String, source : String = ""

        MATH_PLACEHOLDER_RE = /\x00MATH(\d{1,9})\x00/
        # A line whose sole content is one math placeholder — the standalone
        # display-math case, where the emitted <div> starts at line start and
        # is a real CommonMark HTML block. Leading blockquote markers are
        # stripped before the check: `> $$x$$` is block position too (the
        # div becomes an HTML block inside the blockquote).
        BARE_MATH_LINE_RE     = /\A\x00MATH\d+\x00\z/
        BLOCKQUOTE_MARKERS_RE = /\A(?:>[ \t]?)+/
        # Markd-active characters inside a math body rendered in normal
        # inline context (see the branch comments in expand_math). Beyond
        # emphasis/code/link chars, `-`, `.`, and both quotes are included
        # so markd's opt-in smart punctuation can't rewrite `--`/`...`/
        # quotes inside formulas; when smart is off the backslash escapes
        # collapse to the same characters, so output is byte-identical.
        MATH_BODY_MARKD_ACTIVE_RE = /[\\`*_\[\]\-."']/

        # Phase 1: replace `$$…$$` / `$…$` spans with opaque placeholders so
        # the passes running in between can't rewrite formula internals
        # (`$~~x~~$` must reach KaTeX verbatim, not as `$<del>x</del>$`).
        #
        # Fence-aware: `$$` is common in Makefile/shell/Perl code examples,
        # and rewriting it inside a fence corrupts the code block. Display
        # math can span lines, so instead of a per-line walk this buffers
        # runs of non-fence lines and stashes each run as one chunk.
        private def stash_math(content : String) : Tuple(String, Array(MathSpan))
          store = [] of MathSpan
          return {content, store} unless content.includes?('$')

          result = String.build do |io|
            tracker = FenceTracker.new
            chunk = String::Builder.new
            content.each_line(chomp: false) do |line|
              if tracker.fence_line?(line) || line.starts_with?(ENGINE_MARKER_PREFIX)
                if chunk.bytesize > 0
                  io << stash_math_chunk(chunk.to_s, store)
                  chunk = String::Builder.new
                end
                io << line
              else
                chunk << line
              end
            end
            io << stash_math_chunk(chunk.to_s, store) if chunk.bytesize > 0
          end

          {result, store}
        end

        private def stash_math_chunk(text : String, store : Array(MathSpan)) : String
          return text unless text.includes?('$')

          # Code spans — backtick AND `<code>` HTML (a `` `$x$` `` table cell
          # is already `<code>$x$</code>` by now) — are stashed first so
          # their `$…$` stays verbatim. Not via transform_outside_code_spans:
          # a code span captured INSIDE a math body would leave its `\x00CS…`
          # token in the store where the helper's restore step can't see it,
          # so each body is restored explicitly at capture time.
          #
          # Link destinations/titles, reference definitions and raw HTML
          # tags are data, not text, so they are stashed too: a URL with two
          # `$` (`?$filter=a&$top=2`) used to become a math span and break
          # the link. Image alt labels (`![energy $E$](i.png)`) stay literal
          # as well — an `alt` attribute is plain text. Same protected
          # regions as `transform_outside_code_spans`.
          code_spans = [] of String
          stashed = text
          if text.includes?('`')
            stashed = stashed.gsub(SINGLE_LINE_CODE_SPAN_RE) do |match|
              code_spans << match
              "\x00CS#{code_spans.size - 1}\x00"
            end
          end
          if stashed.includes?("<code")
            stashed = stashed.gsub(HTML_CODE_SPAN_RE) do |match|
              code_spans << match
              "\x00CS#{code_spans.size - 1}\x00"
            end
          end
          if stashed.includes?("![")
            stashed = stash_image_labels(stashed, code_spans)
          end
          link_destinations = [] of String
          if stashed.includes?("](") || stashed.includes?("]:")
            stashed = String.build do |io|
              stashed.each_line(chomp: false) do |line|
                io << (line.includes?("](") || line.includes?("]:") ? stash_markdown_link_destinations(line, link_destinations) : line)
              end
            end
          end
          html_tags = [] of String
          if stashed.includes?('<')
            stashed = stashed.gsub(HTML_TAG_RE) do |tag|
              html_tags << tag
              "\x00HT#{html_tags.size - 1}\x00"
            end
            stashed = stashed.gsub(AUTOLINK_RE) do |autolink|
              html_tags << autolink
              "\x00HT#{html_tags.size - 1}\x00"
            end
          end

          result = stashed.gsub(DISPLAY_MATH_RE) do |match|
            store << MathSpan.new(display: true, body: restore_protected($~[1], code_spans, link_destinations, html_tags), source: restore_protected(match, code_spans, link_destinations, html_tags))
            "\x00MATH#{store.size - 1}\x00"
          end

          if result.includes?('$')
            result = result.gsub(INLINE_MATH_RE) do |match|
              store << MathSpan.new(display: false, body: restore_protected($~[1], code_spans, link_destinations, html_tags), source: restore_protected(match, code_spans, link_destinations, html_tags))
              "\x00MATH#{store.size - 1}\x00"
            end
          end

          restore_protected(result, code_spans, link_destinations, html_tags)
        end

        # `content` through the block with its math spans (as the math pass
        # sees them) stashed out, then put back as written — for passes that
        # run before `preprocess` (wikilinks) and must not touch formulas.
        # The block also gets the spans' sources, for `restore_math` on any
        # piece it lifts out (a placeholder must never reach Markd).
        def protect_math(content : String, & : String, Array(String) -> String) : String
          stashed, store = stash_math(content)
          return yield(content, [] of String) if store.empty?
          sources = store.map(&.source)
          restore_math(yield(stashed, sources), sources)
        end

        # `text` with each math placeholder put back as written.
        def restore_math(text : String, sources : Array(String)) : String
          return text if sources.empty? || !text.includes?('\0')
          text.gsub(MATH_PLACEHOLDER_RE) do |match|
            $~[1].to_i?.try { |idx| sources[idx]? } || match
          end
        end

        # Undoes the stashes of `stash_math_chunk` in reverse order: HTML tags
        # (which may hold a link-destination token), then link destinations,
        # then code spans and image labels.
        private def restore_protected(text : String, code_spans : Array(String), link_destinations : Array(String), html_tags : Array(String)) : String
          return text unless text.includes?('\0')
          unless html_tags.empty?
            text = text.gsub(HTML_TAG_TOKEN_RE) { |match| html_tags[$1.to_i]?.try(&.itself) || match }
          end
          unless link_destinations.empty?
            text = text.gsub(LINK_DEST_TOKEN_RE) { |match| link_destinations[$1.to_i]?.try(&.itself) || match }
          end
          restore_code_spans(text, code_spans)
        end

        private def restore_code_spans(text : String, code_spans : Array(String)) : String
          return text if code_spans.empty? || !text.includes?('\0')
          # Reverse order: an HTML code span stashed second can contain a
          # backtick-span placeholder stashed first.
          (code_spans.size - 1).downto(0) do |idx|
            text = text.sub("\x00CS#{idx}\x00", code_spans[idx])
          end
          text
        end

        # `$…$` spans of already-rendered inline HTML (footnote bodies, built
        # after the math pass) wrapped in place, as in a raw HTML block. A
        # span, not a div, for display math: the body sits inside a `<p>`.
        private def wrap_rendered_math(html : String) : String
          return html unless html.includes?('$')
          store = [] of MathSpan
          stashed = stash_math_chunk(html, store)
          return html if store.empty?
          stashed.gsub(MATH_PLACEHOLDER_RE) do |match|
            next match unless span = $~[1].to_i?.try { |idx| store[idx]? }
            body = Utils::TextUtils.escape_xml(HTML.unescape(span.body))
            span.display ? %(<span class="math math-display">\\[#{body}\\]</span>) : %(<span class="math math-inline">\\(#{body}\\)</span>)
          end
        end

        # Phase 2: expand stashed math spans into final HTML.
        #
        # Display math emits single-backslash `\[…\]` in a `<div>` when the
        # div actually lands in HTML-block position — on a line of its own,
        # or inside a raw HTML block. Mid-paragraph `$$…$$` gets a `<span>`
        # instead: there the tags are *inline* raw HTML, Markd inline-parses
        # the content between them (collapsing `\[` to `[`, reading `*`/`_`
        # as emphasis), and a div can't legally sit inside the paragraph
        # anyway. KaTeX/MathJax auto-render keys display style off the
        # `\[…\]` delimiters, not the wrapper tag. Inline math delimiter
        # escaping depends on block context:
        #
        # - In normal inline context the `<span>` content participates in
        #   CommonMark inline parsing, so the delimiters need an extra
        #   backslash — `\\(` in the markdown source collapses to `\(` in
        #   the HTML.
        # - Inside a raw HTML block (a <td>/<dd> hwaro generated, or
        #   author-written block HTML) Markd does no inline parsing and
        #   backslashes ship verbatim, so a single backslash is correct.
        #
        # Walk line by line to track the HTML-block state (a type-6 block
        # runs from its opening tag line to the next blank line).
        private def expand_math(content : String, store : Array(MathSpan)) : String
          return content if store.empty?

          String.build do |io|
            tracker = FenceTracker.new
            in_html_block = false
            content.each_line(chomp: false) do |line|
              if tracker.fence_line?(line) || line.starts_with?(ENGINE_MARKER_PREFIX)
                # Mirrors stash_math's chunk boundaries: block state resets.
                in_html_block = false
                io << line
                next
              end

              if in_html_block
                in_html_block = false if line.strip.empty?
              elsif HTML_BLOCK_START_RE.matches?(line)
                in_html_block = true
              end

              unless line.includes?('\0')
                io << line
                next
              end

              raw_context = in_html_block
              bare_line = line.strip
              bare_line = bare_line.sub(BLOCKQUOTE_MARKERS_RE, "") if bare_line.starts_with?('>')
              bare_display = bare_line.matches?(BARE_MATH_LINE_RE)
              # A multi-line span inside a blockquote carries the `>` markers
              # of its continuation lines: drop them from the formula and put
              # them back after each newline of the emitted HTML, or the
              # escaped `&gt;` lines fall out of the quote (and into KaTeX).
              quote = line[/\A[ \t]*(?:>[ \t]?)+/]?
              io << line.gsub(MATH_PLACEHOLDER_RE) do |match|
                span = $~[1].to_i?.try { |idx| store[idx]? }
                next match unless span

                body = span.body
                # In a raw HTML block the body is HTML text: a generated
                # <td>/<dd> was escaped by InlineMarkdown already, and an
                # author's `&lt;` means `<` there too. Decode once, so the
                # escape below doesn't hand KaTeX a literal `&lt;`.
                body = HTML.unescape(body) if raw_context && body.includes?('&')
                body = body.gsub(/\n[ \t]*(?:>[ \t]?)*/, "\n") if quote && body.includes?('\n')
                escaped = Utils::TextUtils.escape_xml(body)
                escaped = escaped.gsub("\n", "\n#{quote}") if quote
                if span.display && (raw_context || bare_display)
                  "<div class=\"math math-display\">\\[#{escaped}\\]</div>"
                elsif span.display
                  # Mid-paragraph display math (inline raw HTML): escape the
                  # body like the inline branch below, and double the
                  # delimiters' backslashes so `\\[` collapses to `\[`.
                  inline_escaped = escaped.gsub(MATH_BODY_MARKD_ACTIVE_RE) { |c| "\\#{c}" }
                  "<span class=\"math math-display\">\\\\[#{inline_escaped}\\\\]</span>"
                elsif raw_context
                  "<span class=\"math math-inline\">\\(#{escaped}\\)</span>"
                else
                  # Normal inline context: the body still flows through Markd's
                  # CommonMark inline parser, which would (a) read `*`/`_` as
                  # emphasis and pair them across math spans, (b) start code
                  # spans on backticks, (c) form links on `[`/`]`, and (d)
                  # CONSUME a backslash before any ASCII punctuation — stripping
                  # the LaTeX escapes in e.g. `$\{x\}$` or `$a \& b$`. Backslash-
                  # escape each of those active chars (backslash itself FIRST, so
                  # `\{` survives as `\{` rather than being eaten) so Markd ships
                  # the formula body verbatim to KaTeX/MathJax. (`~` is left
                  # alone: GFM strikethrough is handled by hwaro's own
                  # preprocessor, which already skips math spans.)
                  inline_escaped = escaped.gsub(MATH_BODY_MARKD_ACTIVE_RE) { |c| "\\#{c}" }
                  "<span class=\"math math-inline\">\\\\(#{inline_escaped}\\\\)</span>"
                end
              end
            end
          end
        end
      end
    end
  end
end
