# Markdown extensions — math stash/expand around the Markdown pass.
#
# One file per `# --- X ---` pass of the pre/post-processing pipeline; the
# pass ORDER is fixed in ../markdown_extensions.cr (`preprocess` /
# `postprocess`). Parts only reopen the module: no requires, no load-time
# statements (scripts/check_no_toplevel_effects.sh).
module Hwaro
  module Content
    module Processors
      module MarkdownExtensions
        # --- Math ---
        DISPLAY_MATH_RE = InlineMarkdown::DISPLAY_MATH_RE
        INLINE_MATH_RE  = InlineMarkdown::INLINE_MATH_RE
        # Code-span pattern confined to one line, for stashing inside
        # multi-line chunks: a stray lone backtick in one paragraph must not
        # absorb text from another.
        SINGLE_LINE_CODE_SPAN_RE = /`[^`\n]+`/
        # Inline `<code>…</code>` HTML spans — generated by InlineMarkdown
        # for table cells / definition bodies (where the original backticks
        # are already consumed), or author-written raw HTML. Their content
        # is code: the strikethrough/footnote/math passes must treat it as
        # opaque, exactly like backtick spans. `[^<]*` keeps the match to a
        # flat element (generated spans never contain tags); the attribute
        # scan is quote-aware so a `>` inside a quoted value doesn't end
        # the opening tag early.
        HTML_CODE_SPAN_RE = /<code(?:\s(?:[^>"']|"[^"]*"|'[^']*')*)?>[^<]*<\/code>/

        # Placeholder emitted by transform_outside_code_spans for a stashed
        # code span; the capture is the span's index.
        CODE_SPAN_TOKEN_RE = /\x00CS(\d+)\x00/
        # CommonMark "type 6" HTML-block start condition (common block tags,
        # including the <table>/<dl>/<div> markup hwaro itself generates).
        # A line opening one of these starts a raw-HTML block that runs to
        # the next blank line — Markd performs NO inline parsing there, so
        # backslash escapes ship verbatim instead of collapsing.
        HTML_BLOCK_START_RE = /^ {0,3}<\/?(?:address|article|aside|blockquote|caption|center|col|colgroup|dd|details|dialog|div|dl|dt|fieldset|figcaption|figure|footer|form|h[1-6]|header|hr|li|main|menu|nav|ol|p|section|summary|table|tbody|td|tfoot|th|thead|tr|ul)(?:[\s>\/]|\r?$)/i

        # A math span captured by `stash_math`, awaiting `expand_math`.
        record MathSpan, display : Bool, body : String

        MATH_PLACEHOLDER_RE = /\x00MATH(\d+)\x00/
        # A line whose sole content is one math placeholder — the standalone
        # display-math case, where the emitted <div> starts at line start and
        # is a real CommonMark HTML block. Leading blockquote markers are
        # stripped before the check: `> $$x$$` is block position too (the
        # div becomes an HTML block inside the blockquote).
        BARE_MATH_LINE_RE     = /\A\x00MATH\d+\x00\z/
        BLOCKQUOTE_MARKERS_RE = /\A(?:>[ \t]?)+/
        # Markd-active characters inside a math body rendered in normal
        # inline context (see the branch comments in expand_math). Beyond
        # emphasis/code/link chars, `-`, `.`, and both quotes are included
        # so markd's opt-in smart punctuation can't rewrite `--`/`...`/
        # quotes inside formulas; when smart is off the backslash escapes
        # collapse to the same characters, so output is byte-identical.
        MATH_BODY_MARKD_ACTIVE_RE = /[\\`*_\[\]\-."']/

        # One-shot math transform (stash + immediate expand). `preprocess`
        # itself uses the two phases separately so the combined pass runs in
        # between — see the ordering comment there.
        def preprocess_math(content : String) : String
          stashed, store = stash_math(content)
          expand_math(stashed, store)
        end

        # Phase 1: replace `$$…$$` / `$…$` spans with opaque placeholders so
        # the passes running in between can't rewrite formula internals
        # (`$~~x~~$` must reach KaTeX verbatim, not as `$<del>x</del>$`).
        #
        # Fence-aware: `$$` is common in Makefile/shell/Perl code examples,
        # and rewriting it inside a fence corrupts the code block. Display
        # math can span lines, so instead of a per-line walk this buffers
        # runs of non-fence lines and stashes each run as one chunk.
        private def stash_math(content : String) : Tuple(String, Array(MathSpan))
          store = [] of MathSpan
          return {content, store} unless content.includes?('$')

          result = String.build do |io|
            tracker = FenceTracker.new
            chunk = String::Builder.new
            content.each_line(chomp: false) do |line|
              if tracker.fence_line?(line) || line.starts_with?(ENGINE_MARKER_PREFIX)
                if chunk.bytesize > 0
                  io << stash_math_chunk(chunk.to_s, store)
                  chunk = String::Builder.new
                end
                io << line
              else
                chunk << line
              end
            end
            io << stash_math_chunk(chunk.to_s, store) if chunk.bytesize > 0
          end

          {result, store}
        end

        private def stash_math_chunk(text : String, store : Array(MathSpan)) : String
          return text unless text.includes?('$')

          # Code spans — backtick AND `<code>` HTML (a `` `$x$` `` table cell
          # is already `<code>$x$</code>` by now) — are stashed first so
          # their `$…$` stays verbatim. Not via transform_outside_code_spans:
          # a code span captured INSIDE a math body would leave its `\x00CS…`
          # token in the store where the helper's restore step can't see it,
          # so each body is restored explicitly at capture time.
          code_spans = [] of String
          stashed = text
          if text.includes?('`')
            stashed = stashed.gsub(SINGLE_LINE_CODE_SPAN_RE) do |match|
              code_spans << match
              "\x00CS#{code_spans.size - 1}\x00"
            end
          end
          if stashed.includes?("<code")
            stashed = stashed.gsub(HTML_CODE_SPAN_RE) do |match|
              code_spans << match
              "\x00CS#{code_spans.size - 1}\x00"
            end
          end

          result = stashed.gsub(DISPLAY_MATH_RE) do |_|
            store << MathSpan.new(display: true, body: restore_code_spans($~[1], code_spans))
            "\x00MATH#{store.size - 1}\x00"
          end

          if result.includes?('$')
            result = result.gsub(INLINE_MATH_RE) do |_|
              store << MathSpan.new(display: false, body: restore_code_spans($~[1], code_spans))
              "\x00MATH#{store.size - 1}\x00"
            end
          end

          restore_code_spans(result, code_spans)
        end

        private def restore_code_spans(text : String, code_spans : Array(String)) : String
          return text if code_spans.empty? || !text.includes?('\0')
          # Reverse order: an HTML code span stashed second can contain a
          # backtick-span placeholder stashed first.
          (code_spans.size - 1).downto(0) do |idx|
            text = text.sub("\x00CS#{idx}\x00", code_spans[idx])
          end
          text
        end

        # Phase 2: expand stashed math spans into final HTML.
        #
        # Display math emits single-backslash `\[…\]` in a `<div>` when the
        # div actually lands in HTML-block position — on a line of its own,
        # or inside a raw HTML block. Mid-paragraph `$$…$$` gets a `<span>`
        # instead: there the tags are *inline* raw HTML, Markd inline-parses
        # the content between them (collapsing `\[` to `[`, reading `*`/`_`
        # as emphasis), and a div can't legally sit inside the paragraph
        # anyway. KaTeX/MathJax auto-render keys display style off the
        # `\[…\]` delimiters, not the wrapper tag. Inline math delimiter
        # escaping depends on block context:
        #
        # - In normal inline context the `<span>` content participates in
        #   CommonMark inline parsing, so the delimiters need an extra
        #   backslash — `\\(` in the markdown source collapses to `\(` in
        #   the HTML.
        # - Inside a raw HTML block (a <td>/<dd> hwaro generated, or
        #   author-written block HTML) Markd does no inline parsing and
        #   backslashes ship verbatim, so a single backslash is correct.
        #
        # Walk line by line to track the HTML-block state (a type-6 block
        # runs from its opening tag line to the next blank line).
        private def expand_math(content : String, store : Array(MathSpan)) : String
          return content if store.empty?

          String.build do |io|
            tracker = FenceTracker.new
            in_html_block = false
            content.each_line(chomp: false) do |line|
              if tracker.fence_line?(line) || line.starts_with?(ENGINE_MARKER_PREFIX)
                # Mirrors stash_math's chunk boundaries: block state resets.
                in_html_block = false
                io << line
                next
              end

              if in_html_block
                in_html_block = false if line.strip.empty?
              elsif HTML_BLOCK_START_RE.matches?(line)
                in_html_block = true
              end

              unless line.includes?('\0')
                io << line
                next
              end

              raw_context = in_html_block
              bare_line = line.strip
              bare_line = bare_line.sub(BLOCKQUOTE_MARKERS_RE, "") if bare_line.starts_with?('>')
              bare_display = bare_line.matches?(BARE_MATH_LINE_RE)
              io << line.gsub(MATH_PLACEHOLDER_RE) do |match|
                span = $~[1].to_i?.try { |idx| store[idx]? }
                next match unless span

                escaped = Utils::TextUtils.escape_xml(span.body)
                if span.display && (raw_context || bare_display)
                  "<div class=\"math math-display\">\\[#{escaped}\\]</div>"
                elsif span.display
                  # Mid-paragraph display math (inline raw HTML): escape the
                  # body like the inline branch below, and double the
                  # delimiters' backslashes so `\\[` collapses to `\[`.
                  inline_escaped = escaped.gsub(MATH_BODY_MARKD_ACTIVE_RE) { |c| "\\#{c}" }
                  "<span class=\"math math-display\">\\\\[#{inline_escaped}\\\\]</span>"
                elsif raw_context
                  "<span class=\"math math-inline\">\\(#{escaped}\\)</span>"
                else
                  # Normal inline context: the body still flows through Markd's
                  # CommonMark inline parser, which would (a) read `*`/`_` as
                  # emphasis and pair them across math spans, (b) start code
                  # spans on backticks, (c) form links on `[`/`]`, and (d)
                  # CONSUME a backslash before any ASCII punctuation — stripping
                  # the LaTeX escapes in e.g. `$\{x\}$` or `$a \& b$`. Backslash-
                  # escape each of those active chars (backslash itself FIRST, so
                  # `\{` survives as `\{` rather than being eaten) so Markd ships
                  # the formula body verbatim to KaTeX/MathJax. (`~` is left
                  # alone: GFM strikethrough is handled by hwaro's own
                  # preprocessor, which already skips math spans.)
                  inline_escaped = escaped.gsub(MATH_BODY_MARKD_ACTIVE_RE) { |c| "\\#{c}" }
                  "<span class=\"math math-inline\">\\\\(#{inline_escaped}\\\\)</span>"
                end
              end
            end
          end
        end
      end
    end
  end
end
