module Hwaro
  module Services
    module Defaults
      class ContentSamples
        def self.index_content : String
          <<-CONTENT
+++
title = "Welcome to Hwaro"
tags = ["welcome", "getting-started"]
+++

# Hello, Hwaro!

This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).

## Getting Started

1. Edit `content/index.md` to change this page.
2. Add new `.md` files in `content/` to create new pages.
3. Run `hwaro build` to regenerate the site.
4. Run `hwaro serve` to preview changes locally.

## Taxonomies

Hwaro supports taxonomies like tags and categories. Check out:

- [All Tags](/tags/)
- [All Categories](/categories/)
CONTENT
        end

        def self.about_content : String
          <<-CONTENT
+++
title = "About"
tags = ["about", "info"]
categories = ["pages"]
+++

# About Us

This is an about page to demonstrate multiple pages.
CONTENT
        end

        def self.blog_index_content : String
          <<-CONTENT
+++
title = "Blog"
+++

# Blog

Welcome to the blog section. Here you'll find all our posts.
CONTENT
        end

        def self.blog_post_content : String
          <<-CONTENT
+++
title = "Hello World"
date = "2024-01-01"
tags = ["hello", "getting-started"]
categories = ["blog"]
authors = ["hwaro"]
+++

# Hello World

This is a sample blog post demonstrating taxonomies in Hwaro.

## Tags and Categories

This post has been tagged with `hello` and `getting-started`, and belongs to the `blog` category.

You can browse:

- [All posts tagged "hello"](/tags/hello/)
- [All posts in "blog" category](/categories/blog/)
CONTENT
        end

        def self.index_content_simple : String
          <<-CONTENT
+++
title = "Welcome to Hwaro"
+++

# Hello, Hwaro!

This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).

## Getting Started

1. Edit `content/index.md` to change this page.
2. Add new `.md` files in `content/` to create new pages.
3. Run `hwaro build` to regenerate the site.
4. Run `hwaro serve` to preview changes locally.
CONTENT
        end

        def self.about_content_simple : String
          <<-CONTENT
+++
title = "About"
+++

# About Us

This is an about page to demonstrate multiple pages.
CONTENT
        end
      end
    end
  end
end
