module Hwaro
  module Services
    module Defaults
      class ContentSamples
        def self.index_content : String
          <<-CONTENT
+++
title = "Welcome to Hwaro"
tags = ["welcome", "getting-started"]
+++

# Hello, Hwaro!

This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).

## Getting Started

1. Edit `content/index.md` to change this page.
2. Add new `.md` files in `content/` to create new pages.
3. Run `hwaro build` to regenerate the site.
4. Run `hwaro serve` to preview changes locally.

## Taxonomies

Hwaro supports taxonomies like tags and categories. Check out:

- [All Tags](/tags/)
- [All Categories](/categories/)
CONTENT
        end

        def self.about_content : String
          <<-CONTENT
+++
title = "About"
tags = ["about", "info"]
categories = ["pages"]
+++

# About Us

This is an about page to demonstrate multiple pages.
CONTENT
        end

        def self.blog_index_content : String
          <<-CONTENT
+++
title = "Blog"
+++

# Blog

Welcome to the blog section. Here you'll find all our posts.
CONTENT
        end

        def self.blog_post_content : String
          <<-CONTENT
+++
title = "Hello World"
date = "2024-01-01"
tags = ["hello", "getting-started"]
categories = ["blog"]
authors = ["hwaro"]
+++

# Hello World

This is a sample blog post demonstrating taxonomies in Hwaro.

## Tags and Categories

This post has been tagged with `hello` and `getting-started`, and belongs to the `blog` category.

You can browse:

- [All posts tagged "hello"](/tags/hello/)
- [All posts in "blog" category](/categories/blog/)
CONTENT
        end

        def self.index_content_simple : String
          <<-CONTENT
+++
title = "Welcome to Hwaro"
+++

# Hello, Hwaro!

This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).

## Getting Started

1. Edit `content/index.md` to change this page.
2. Add new `.md` files in `content/` to create new pages.
3. Run `hwaro build` to regenerate the site.
4. Run `hwaro serve` to preview changes locally.
CONTENT
        end

        def self.about_content_simple : String
          <<-CONTENT
+++
title = "About"
+++

# About Us

This is an about page to demonstrate multiple pages.
CONTENT
        end

        # Multilingual content generators
        def self.index_content_multilingual(lang : String, is_default : Bool, skip_taxonomies : Bool = false) : String
          title = index_title(lang)
          greeting = index_greeting(lang)
          description = index_description(lang)
          getting_started = getting_started_title(lang)
          steps = getting_started_steps(lang, is_default)

          taxonomies_section = skip_taxonomies ? "" : taxonomies_intro(lang)

          String.build do |str|
            str << "+++\n"
            str << "title = \"#{title}\"\n"
            str << "tags = [\"welcome\", \"getting-started\"]\n" unless skip_taxonomies
            str << "+++\n\n"
            str << "# #{greeting}\n\n"
            str << "#{description}\n\n"
            str << "## #{getting_started}\n\n"
            str << "#{steps}\n"
            str << "#{taxonomies_section}\n" unless taxonomies_section.empty?
          end
        end

        def self.about_content_multilingual(lang : String, skip_taxonomies : Bool = false) : String
          title = about_title(lang)
          heading = about_heading(lang)
          body = about_body(lang)

          if skip_taxonomies
            String.build do |str|
              str << "+++\n"
              str << "title = \"#{title}\"\n"
              str << "+++\n\n"
              str << "# #{heading}\n\n"
              str << "#{body}\n"
            end
          else
            String.build do |str|
              str << "+++\n"
              str << "title = \"#{title}\"\n"
              str << "tags = [\"about\", \"info\"]\n"
              str << "categories = [\"pages\"]\n"
              str << "+++\n\n"
              str << "# #{heading}\n\n"
              str << "#{body}\n"
            end
          end
        end

        def self.blog_index_content_multilingual(lang : String) : String
          title = blog_title(lang)
          intro = blog_intro(lang)

          <<-CONTENT
+++
title = "#{title}"
+++

# #{title}

#{intro}
CONTENT
        end

        def self.blog_post_content_multilingual(lang : String, skip_taxonomies : Bool = false) : String
          title = hello_world_title(lang)
          body = hello_world_body(lang)

          if skip_taxonomies
            String.build do |str|
              str << "+++\n"
              str << "title = \"#{title}\"\n"
              str << "date = \"2024-01-01\"\n"
              str << "+++\n\n"
              str << "# #{title}\n\n"
              str << "#{body}\n"
            end
          else
            String.build do |str|
              str << "+++\n"
              str << "title = \"#{title}\"\n"
              str << "date = \"2024-01-01\"\n"
              str << "tags = [\"hello\", \"getting-started\"]\n"
              str << "categories = [\"blog\"]\n"
              str << "authors = [\"hwaro\"]\n"
              str << "+++\n\n"
              str << "# #{title}\n\n"
              str << "#{body}\n"
            end
          end
        end

        # Language-specific strings
        private def self.index_title(lang : String) : String
          case lang
          when "ko" then "Hwaro에 오신 것을 환영합니다"
          when "ja" then "Hwaroへようこそ"
          when "zh" then "欢迎使用Hwaro"
          when "es" then "Bienvenido a Hwaro"
          when "fr" then "Bienvenue sur Hwaro"
          when "de" then "Willkommen bei Hwaro"
          else "Welcome to Hwaro"
          end
        end

        private def self.index_greeting(lang : String) : String
          case lang
          when "ko" then "안녕하세요, Hwaro!"
          when "ja" then "こんにちは、Hwaro！"
          when "zh" then "你好，Hwaro！"
          when "es" then "¡Hola, Hwaro!"
          when "fr" then "Bonjour, Hwaro !"
          when "de" then "Hallo, Hwaro!"
          else "Hello, Hwaro!"
          end
        end

        private def self.index_description(lang : String) : String
          case lang
          when "ko" then "[Hwaro](https://github.com/hahwul/hwaro)로 생성된 정적 사이트입니다."
          when "ja" then "[Hwaro](https://github.com/hahwul/hwaro)で生成された静的サイトです。"
          when "zh" then "这是一个由[Hwaro](https://github.com/hahwul/hwaro)生成的静态网站。"
          when "es" then "Este es un sitio estático generado por [Hwaro](https://github.com/hahwul/hwaro)."
          when "fr" then "Ceci est un site statique généré par [Hwaro](https://github.com/hahwul/hwaro)."
          when "de" then "Dies ist eine statische Website, die mit [Hwaro](https://github.com/hahwul/hwaro) erstellt wurde."
          else "This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro)."
          end
        end

        private def self.getting_started_title(lang : String) : String
          case lang
          when "ko" then "시작하기"
          when "ja" then "はじめに"
          when "zh" then "开始使用"
          when "es" then "Primeros pasos"
          when "fr" then "Pour commencer"
          when "de" then "Erste Schritte"
          else "Getting Started"
          end
        end

        private def self.getting_started_steps(lang : String, is_default : Bool) : String
          content_path = is_default ? "content" : "content/#{lang}"
          case lang
          when "ko"
            "1. `#{content_path}/index.md`를 편집하여 이 페이지를 수정하세요.\n" \
            "2. `#{content_path}/`에 새 `.md` 파일을 추가하여 새 페이지를 만드세요.\n" \
            "3. `hwaro build`를 실행하여 사이트를 다시 생성하세요.\n" \
            "4. `hwaro serve`를 실행하여 로컬에서 미리보기 하세요."
          when "ja"
            "1. `#{content_path}/index.md`を編集してこのページを変更します。\n" \
            "2. `#{content_path}/`に新しい`.md`ファイルを追加して新しいページを作成します。\n" \
            "3. `hwaro build`を実行してサイトを再生成します。\n" \
            "4. `hwaro serve`を実行してローカルでプレビューします。"
          else
            "1. Edit `#{content_path}/index.md` to change this page.\n" \
            "2. Add new `.md` files in `#{content_path}/` to create new pages.\n" \
            "3. Run `hwaro build` to regenerate the site.\n" \
            "4. Run `hwaro serve` to preview changes locally."
          end
        end

        private def self.taxonomies_intro(lang : String) : String
          case lang
          when "ko"
            "\n## 분류 체계\n\n" \
            "Hwaro는 태그와 카테고리 같은 분류 체계를 지원합니다:\n\n" \
            "- [모든 태그](/ko/tags/)\n" \
            "- [모든 카테고리](/ko/categories/)"
          when "ja"
            "\n## タクソノミー\n\n" \
            "Hwaroはタグやカテゴリなどのタクソノミーをサポートしています：\n\n" \
            "- [すべてのタグ](/ja/tags/)\n" \
            "- [すべてのカテゴリ](/ja/categories/)"
          else
            "\n## Taxonomies\n\n" \
            "Hwaro supports taxonomies like tags and categories. Check out:\n\n" \
            "- [All Tags](/tags/)\n" \
            "- [All Categories](/categories/)"
          end
        end

        private def self.about_title(lang : String) : String
          case lang
          when "ko" then "소개"
          when "ja" then "について"
          when "zh" then "关于"
          when "es" then "Acerca de"
          when "fr" then "À propos"
          when "de" then "Über uns"
          else "About"
          end
        end

        private def self.about_heading(lang : String) : String
          case lang
          when "ko" then "소개"
          when "ja" then "私たちについて"
          when "zh" then "关于我们"
          when "es" then "Sobre nosotros"
          when "fr" then "À propos de nous"
          when "de" then "Über uns"
          else "About Us"
          end
        end

        private def self.about_body(lang : String) : String
          case lang
          when "ko" then "여러 페이지를 보여주기 위한 소개 페이지입니다."
          when "ja" then "複数のページを示すための紹介ページです。"
          when "zh" then "这是一个展示多页面的关于页面。"
          when "es" then "Esta es una página de presentación para demostrar múltiples páginas."
          when "fr" then "Ceci est une page de présentation pour démontrer plusieurs pages."
          when "de" then "Dies ist eine Über-uns-Seite, um mehrere Seiten zu demonstrieren."
          else "This is an about page to demonstrate multiple pages."
          end
        end

        private def self.blog_title(lang : String) : String
          case lang
          when "ko" then "블로그"
          when "ja" then "ブログ"
          when "zh" then "博客"
          when "es" then "Blog"
          when "fr" then "Blog"
          when "de" then "Blog"
          else "Blog"
          end
        end

        private def self.blog_intro(lang : String) : String
          case lang
          when "ko" then "블로그 섹션에 오신 것을 환영합니다. 여기서 모든 게시물을 확인하실 수 있습니다."
          when "ja" then "ブログセクションへようこそ。ここですべての投稿をご覧いただけます。"
          when "zh" then "欢迎来到博客区。在这里您可以找到所有的文章。"
          when "es" then "Bienvenido a la sección del blog. Aquí encontrarás todas nuestras publicaciones."
          when "fr" then "Bienvenue dans la section blog. Vous trouverez ici tous nos articles."
          when "de" then "Willkommen im Blog-Bereich. Hier finden Sie alle unsere Beiträge."
          else "Welcome to the blog section. Here you'll find all our posts."
          end
        end

        private def self.hello_world_title(lang : String) : String
          case lang
          when "ko" then "안녕 세상"
          when "ja" then "ハローワールド"
          when "zh" then "你好世界"
          when "es" then "Hola Mundo"
          when "fr" then "Bonjour le monde"
          when "de" then "Hallo Welt"
          else "Hello World"
          end
        end

        private def self.hello_world_body(lang : String) : String
          case lang
          when "ko" then "Hwaro의 분류 체계를 보여주는 샘플 블로그 포스트입니다."
          when "ja" then "Hwaroのタクソノミーを示すサンプルブログ記事です。"
          when "zh" then "这是一个展示Hwaro分类功能的示例博客文章。"
          when "es" then "Esta es una publicación de blog de ejemplo que demuestra las taxonomías en Hwaro."
          when "fr" then "Ceci est un exemple d'article de blog démontrant les taxonomies dans Hwaro."
          when "de" then "Dies ist ein Beispiel-Blogbeitrag, der Taxonomien in Hwaro demonstriert."
          else "This is a sample blog post demonstrating taxonomies in Hwaro."
          end
        end
      end
    end
  end
end
