module Hwaro
  module Services
    module Defaults
      class ContentSamples
        def self.index_content : String
          <<-CONTENT
            +++
            title = "Welcome to Hwaro"
            +++

            # Hello, Hwaro!

            This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).

            ## Getting Started

            1. Edit `content/index.md` to change this page.
            2. Add new `.md` files in `content/` to create new pages.
            3. Run `hwaro build` to regenerate the site.
            4. Run `hwaro serve` to preview changes locally.
          CONTENT
        end

        def self.about_content : String
          <<-CONTENT
            +++
            title = "About"
            +++

            # About Us

            This is an about page to demonstrate multiple pages.
          CONTENT
        end
      end
    end
  end
end
