# Bare scaffold - minimal structure with semantic HTML only
#
# Generates only directory structure and config.toml with
# semantic HTML templates. No CSS styles, no search JS,
# no opinionated templates.

require "./base"

module Hwaro
  module Services
    module Scaffolds
      class Bare < Base
        def type : Config::Options::ScaffoldType
          Config::Options::ScaffoldType::Bare
        end

        def description : String
          "Minimal structure with semantic HTML only (no styles, no JS)"
        end

        def content_files(skip_taxonomies : Bool = false) : Hash(String, String)
          {
            "index.md" => index_content,
            "about.md" => about_content,
          }
        end

        def template_files(skip_taxonomies : Bool = false) : Hash(String, String)
          files = {
            "header.html"  => bare_header_template,
            "footer.html"  => bare_footer_template,
            "page.html"    => page_template,
            "section.html" => bare_section_template,
            "404.html"     => bare_not_found_template,
          }

          unless skip_taxonomies
            files["taxonomy.html"] = bare_taxonomy_template
            files["taxonomy_term.html"] = bare_taxonomy_term_template
          end

          files
        end

        def static_files : Hash(String, String)
          {} of String => String
        end

        def shortcode_files : Hash(String, String)
          {} of String => String
        end

        def config_content(skip_taxonomies : Bool = false) : String
          config = String.build do |str|
            str << base_config
            str << plugins_config
            str << content_files_config
            str << taxonomies_config unless skip_taxonomies
            str << sitemap_config
            str << feeds_config
          end
          config
        end

        # Bare header: semantic HTML only, no styles
        private def bare_header_template : String
          <<-HTML
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="description" content="{{ page.description }}">
            <title>{{ page.title }} - {{ site.title }}</title>
          </head>
          <body>
            <header>
              <a href="{{ base_url }}/">{{ site.title }}</a>
              <nav>
                <a href="{{ base_url }}/">Home</a>
                <a href="{{ base_url }}/about/">About</a>
              </nav>
            </header>

          HTML
        end

        # Bare footer: semantic HTML only
        private def bare_footer_template : String
          <<-HTML
              <footer>
                <p>Powered by Hwaro</p>
              </footer>
          </body>
          </html>
          HTML
        end

        # Bare section template
        private def bare_section_template : String
          <<-HTML
          {% include "header.html" %}
            <main>
              <h1>{{ page.title }}</h1>
              {{ content }}
              <ul>
                {{ section.list }}
              </ul>
              {{ pagination }}
            </main>
          {% include "footer.html" %}
          HTML
        end

        # Bare 404 template
        private def bare_not_found_template : String
          <<-HTML
          {% include "header.html" %}
            <main>
              <h1>404 Not Found</h1>
              <p>The page you are looking for does not exist.</p>
              <p><a href="{{ base_url }}/">Return to Home</a></p>
            </main>
          {% include "footer.html" %}
          HTML
        end

        # Bare taxonomy template
        private def bare_taxonomy_template : String
          <<-HTML
          {% include "header.html" %}
            <main>
              <h1>{{ page.title }}</h1>
              {{ content }}
            </main>
          {% include "footer.html" %}
          HTML
        end

        # Bare taxonomy term template
        private def bare_taxonomy_term_template : String
          <<-HTML
          {% include "header.html" %}
            <main>
              <h1>{{ page.title }}</h1>
              {{ content }}
            </main>
          {% include "footer.html" %}
          HTML
        end

        private def index_content : String
          <<-CONTENT
          +++
          title = "Welcome to Hwaro"
          +++

          # Hello, Hwaro!

          This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).
          CONTENT
        end

        private def about_content : String
          <<-CONTENT
          +++
          title = "About"
          +++

          # About

          This is an about page.
          CONTENT
        end
      end
    end
  end
end
