# Simple scaffold - basic pages structure
#
# This is the default scaffold that creates a minimal site with
# just a homepage and about page.

require "./base"

module Hwaro
  module Services
    module Scaffolds
      class Simple < Base
        def type : Config::Options::ScaffoldType
          Config::Options::ScaffoldType::Simple
        end

        def description : String
          "Basic pages structure with homepage and about page"
        end

        def content_files(skip_taxonomies : Bool = false) : Hash(String, String)
          files = {} of String => String

          if skip_taxonomies
            files["index.md"] = index_content_simple
            files["about.md"] = about_content_simple
          else
            files["index.md"] = index_content
            files["about.md"] = about_content
          end

          files
        end

        def template_files(skip_taxonomies : Bool = false) : Hash(String, String)
          files = {
            "header.ecr"  => header_template,
            "footer.ecr"  => footer_template,
            "page.ecr"    => page_template,
            "section.ecr" => section_template,
            "404.ecr"     => not_found_template,
          }

          unless skip_taxonomies
            files["taxonomy.ecr"] = taxonomy_template
            files["taxonomy_term.ecr"] = taxonomy_term_template
          end

          files
        end

        def config_content(skip_taxonomies : Bool = false) : String
          config = String.build do |str|
            str << base_config
            str << search_config
            str << sitemap_config
            str << robots_config
            str << llms_config
            str << feeds_config
            str << plugins_config
            str << highlight_config
            str << build_hooks_config
            str << taxonomies_config unless skip_taxonomies
          end
          config
        end

        # Content files
        private def index_content : String
          <<-CONTENT
+++
title = "Welcome to Hwaro"
tags = ["welcome", "getting-started"]
+++

# Hello, Hwaro!

This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).

## Getting Started

1. Edit `content/index.md` to change this page.
2. Add new `.md` files in `content/` to create new pages.
3. Run `hwaro build` to regenerate the site.
4. Run `hwaro serve` to preview changes locally.

## Taxonomies

Hwaro supports taxonomies like tags and categories. Check out:

- [All Tags](/tags/)
- [All Categories](/categories/)
CONTENT
        end

        private def index_content_simple : String
          <<-CONTENT
+++
title = "Welcome to Hwaro"
+++

# Hello, Hwaro!

This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).

## Getting Started

1. Edit `content/index.md` to change this page.
2. Add new `.md` files in `content/` to create new pages.
3. Run `hwaro build` to regenerate the site.
4. Run `hwaro serve` to preview changes locally.
CONTENT
        end

        private def about_content : String
          <<-CONTENT
+++
title = "About"
tags = ["about", "info"]
categories = ["pages"]
+++

# About Us

This is an about page to demonstrate multiple pages.
CONTENT
        end

        private def about_content_simple : String
          <<-CONTENT
+++
title = "About"
+++

# About Us

This is an about page to demonstrate multiple pages.
CONTENT
        end
      end
    end
  end
end
