# Simple scaffold - basic pages structure
#
# This is the default scaffold that creates a minimal site with
# just a homepage and about page.

require "./base"

module Hwaro
  module Services
    module Scaffolds
      class Simple < Base
        def type : Config::Options::ScaffoldType
          Config::Options::ScaffoldType::Simple
        end

        def description : String
          "Homepage, about page, taxonomies (tags/categories/authors), and a search index"
        end

        def content_files(skip_taxonomies : Bool = false) : Hash(String, String)
          {
            "index.md" => index_content(skip_taxonomies),
            "about.md" => about_content(skip_taxonomies),
          }
        end

        # Ship the embedded Charter (Charis SIL) faces the inline
        # stylesheet's `@font-face` blocks reference, alongside the
        # inherited favicon.
        def static_files : Hash(String, String)
          super.merge(font_files)
        end

        # Pages the menus/nav link to (kept as stubs by --skip-sample-content).
        protected def skeleton_page_paths : Array(String)
          ["index.md", "about.md"]
        end

        def template_files(skip_taxonomies : Bool = false) : Hash(String, String)
          files = {
            "header.html"  => header_template,
            "footer.html"  => footer_template,
            "page.html"    => page_template,
            "section.html" => section_template,
            "404.html"     => not_found_template,
          }

          unless skip_taxonomies
            files["taxonomy.html"] = taxonomy_template
            files["taxonomy_term.html"] = taxonomy_term_template
          end

          files
        end

        # `[[menus.main]]` entries backing `Base#navigation`
        # (`{% for item in get_menu(name="main") %}`) — matches the two
        # links the scaffold's own content creates (index.md, about.md).
        # Add a third entry here (or register a page/section into "main"
        # from its own front matter with `menus = ["main"]`) to extend the
        # nav without touching a template. Multilingual projects also get
        # `[[languages.<code>.menus.main]]` mirrors with locale-prefixed
        # URLs (see `Base#main_menu_toml`).
        private def menu_entries_toml(multilingual_languages : Array(String) = [] of String) : String
          main_menu_toml([{"Home", "/"}, {"About", "/about/"}], multilingual_languages)
        end

        # `--full-config` path: same entries as `minimal_config_content`
        # below, with a discoverability banner matching the rest of
        # `config_content`'s commented sections.
        protected def menus_config(multilingual_languages : Array(String) = [] of String) : String
          banner = <<-TOML

            # =============================================================================
            # Menus
            # =============================================================================
            # Named navigation menus, rendered in templates/header.html via
            # {% for item in get_menu(name="main") %}. Add/reorder entries
            # here, or register a page/section into "main" from its own
            # front matter with `menus = ["main"]` — no template edit
            # required either way.
            TOML
          banner + menu_entries_toml(multilingual_languages)
        end

        # `hwaro init`'s DEFAULT path (no `--full-config`) and
        # `--minimal-config` both build on `minimal_config_content`, NOT
        # `config_content` — without this override, `Base#navigation`'s
        # `get_menu(name="main")` would resolve against a config with no
        # `[[menus.*]]` at all, rendering an empty nav out of the box.
        def minimal_config_content(skip_taxonomies : Bool = false, multilingual_languages : Array(String) = [] of String) : String
          super + menu_entries_toml(multilingual_languages)
        end

        # Content files. Bodies intentionally start at level 2 — `page.html`
        # renders `page.title` as `<h1>`, so a body `# Title` would duplicate
        # it (gh#525). `--skip-taxonomies` drops the taxonomy front matter
        # and the paragraphs that point at taxonomy pages / menus.
        private def index_content(skip_taxonomies : Bool) : String
          tags = skip_taxonomies ? "" : %(\ntags = ["welcome", "getting-started"])
          browse = skip_taxonomies ? "" : "\n\nReaders can also browse this site by [Tags](/tags/) or [Categories](/categories/)."
          <<-CONTENT
            +++
            title = "Welcome to Hwaro"
            description = "A fresh static site generated by Hwaro."#{tags}
            +++

            Your site is live, and everything on this page is yours to rewrite. It is built with [Hwaro](https://github.com/hahwul/hwaro), a fast static site generator written in Crystal.

            ## Start here

            1. Edit `content/index.md` and make this page say something true.
            2. Add Markdown files under `content/` to grow the site.
            3. Run `hwaro serve` to preview changes with live reload.
            4. Run `hwaro build` when you are ready to publish.

            ---

            ## Where things live

            - `content/` holds every page as plain Markdown.
            - `templates/` shapes the HTML around it.
            - `static/` is copied through untouched.
            - `config.toml` turns features on and off.#{browse}
            CONTENT
        end

        private def about_content(skip_taxonomies : Bool) : String
          taxonomies = skip_taxonomies ? "" : %(\ntags = ["about"]\ncategories = ["pages"])
          menu = skip_taxonomies ? "" : "\n\n## Adding pages to the menu\n\nThe navigation is menu-driven: add a `[[menus.main]]` entry in `config.toml` (or set `menus = [\"main\"]` in a page's front matter) and the header picks it up. No template edits needed."
          <<-CONTENT
            +++
            title = "About"
            description = "A short introduction to this site and its author."#{taxonomies}
            +++

            Hello! This site is built with [Hwaro](https://github.com/hahwul/hwaro), a static site generator written in Crystal.

            ## Make it yours

            Edit `content/about.md` and tell readers, in a paragraph or two:

            - who writes here,
            - what the site covers, and
            - how to reach you.

            One honest paragraph beats any template text. Delete the rest of this page once it's written.#{menu}
            CONTENT
        end
      end
    end
  end
end
