module Hwaro
  class Init
    def run(target_path : String)
      puts "Initializing new Hwaro project in #{target_path}..."

      unless Dir.exists?(target_path)
        Dir.mkdir_p(target_path)
      end

      create_directory(File.join(target_path, "content"))
      create_file(File.join(target_path, "content", "index.md"), sample_content)
      create_file(File.join(target_path, "content", "about.md"), sample_about_content)

      create_directory(File.join(target_path, "layouts"))
      create_file(File.join(target_path, "layouts", "default.ecr"), sample_layout)

      create_directory(File.join(target_path, "static"))
      create_file(File.join(target_path, "config.toml"), sample_config)

      puts "Done! Run `hwaro build` to generate the site."
      unless target_path == "."
        puts "  cd #{target_path}"
      end
    end

    private def create_directory(path : String)
      unless Dir.exists?(path)
        Dir.mkdir_p(path)
        puts "Created directory: #{path}"
      else
        puts "Skipped directory: #{path} (already exists)"
      end
    end

    private def create_file(path : String, content : String)
      unless File.exists?(path)
        File.write(path, content)
        puts "Created file: #{path}"
      else
        puts "Skipped file: #{path} (already exists)"
      end
    end

    private def sample_content
      <<-CONTENT
      +++
      title = "Welcome to Hwaro"
      +++

      # Hello, Hwaro!

      This is a fresh static site generated by [Hwaro](https://github.com/hahwul/hwaro).

      ## Getting Started

      1. Edit `content/index.md` to change this page.
      2. Add new `.md` files in `content/` to create new pages.
      3. Run `hwaro build` to regenerate the site.
      4. Run `hwaro serve` to preview changes locally.
      CONTENT
    end

    private def sample_about_content
      <<-CONTENT
      +++
      title = "About"
      +++

      # About Us

      This is an about page to demonstrate multiple pages.
      CONTENT
    end

    private def sample_layout
      <<-HTML
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><%= page_title %></title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 2rem; color: #333; }
          header { margin-bottom: 2rem; border-bottom: 1px solid #eaeaea; padding-bottom: 1rem; }
          h1, h2, h3 { line-height: 1.2; }
          nav a { margin-right: 1rem; text-decoration: none; color: #0070f3; }
          nav a:hover { text-decoration: underline; }
          footer { margin-top: 3rem; border-top: 1px solid #eaeaea; padding-top: 1rem; color: #666; font-size: 0.9rem; text-align: center; }
          code { background: #f4f4f4; padding: 0.2rem 0.4rem; border-radius: 3px; font-size: 0.9em; }
        </style>
      </head>
      <body>
        <header>
          <nav>
            <a href="/">Home</a>
            <a href="/about.html">About</a>
          </nav>
        </header>

        <main>
          <%= content %>
        </main>

        <footer>
          <p>Powered by Hwaro</p>
        </footer>
      </body>
      </html>
      HTML
    end

    private def sample_config
      <<-CONTENT
      title = "My Hwaro Site"
      base_url = "http://localhost:3000"
      CONTENT
    end
  end
end
