/* Hwaro built-in search UI. Generated by hwaro: no dependencies, no network
   requests beyond this site's own search index. Configured by the
   data-hwaro-search-config attribute of its <script> tag ({{ search_tags }}).
   Index data reaches the page only through textContent and text nodes,
   never parsed as markup. */
(function () {
  "use strict";

  var MAX_RESULTS = 20;
  var EXCERPT_LENGTH = 160;
  var MAX_CHIPS = 12;

  // Mirrors Utils::TextUtils.cjk_char? so query bigrams line up with the
  // index-side `tokenize_cjk` output.
  function isCjk(ch) {
    var c = ch.codePointAt(0);
    return (c >= 0x4e00 && c <= 0x9fff) || (c >= 0x3040 && c <= 0x30ff) ||
      (c >= 0xac00 && c <= 0xd7af) || (c >= 0x1100 && c <= 0x11ff) ||
      (c >= 0x3400 && c <= 0x4dbf) || (c >= 0x3300 && c <= 0x33ff) ||
      (c >= 0xfe30 && c <= 0xfe4f);
  }

  // Display text for an index string stored as `tokenize_cjk` bigrams:
  // "검색 색엔 엔진" reads back as "검색엔진". Matching still runs on the
  // stored form. ponytail: two real words where the second starts with the
  // first's last CJK character also merge; display only.
  var CJK_CLASS = "[\u1100-\u11ff\u3040-\u30ff\u3300-\u4dbf\u4e00-\u9fff\uac00-\ud7af\ufe30-\ufe4f]";
  var BIGRAM_SEAM = new RegExp("(" + CJK_CLASS + ") \\1(?=" + CJK_CLASS + ")", "g");
  function untokenize(text) {
    return String(text).replace(BIGRAM_SEAM, "$1");
  }

  // Lowercased query tokens. With `cjk`, a CJK run becomes its overlapping
  // bigrams (a single character stays as is) and the text around it its
  // own token, the way the index side tokenized the stored text.
  function tokenize(query, cjk) {
    var words = String(query).toLowerCase().split(/\s+/).filter(Boolean);
    if (!cjk) return words;
    var out = [];
    words.forEach(function (word) {
      var run = [], rest = "";
      var flush = function () {
        if (run.length === 1) out.push(run[0]);
        for (var i = 0; i + 1 < run.length; i++) out.push(run[i] + run[i + 1]);
        run = [];
      };
      Array.from(word).forEach(function (ch) {
        if (isCjk(ch)) {
          if (rest) { out.push(rest); rest = ""; }
          run.push(ch);
        } else {
          flush();
          rest += ch;
        }
      });
      flush();
      if (rest) out.push(rest);
    });
    return out;
  }

  // Weight of `token` in `text`: 0 when absent, doubled at a word start.
  function fieldScore(text, token, weight) {
    var i = text.indexOf(token);
    if (i < 0 || !weight) return 0;
    return i === 0 || /[\s\-_./:(]/.test(text.charAt(i - 1)) ? weight * 2 : weight;
  }

  function lower(value) {
    return typeof value === "string" ? value.toLowerCase() : "";
  }

  // Score of one record: every token must match somewhere (AND). Title
  // beats heading beats content. A section record (one with a heading)
  // weighs its page title lower, so a title query ranks the page first.
  function scoreRecord(record, tokens) {
    var title = lower(record.title), heading = lower(record.heading);
    var content = lower(record.content), description = lower(record.description);
    var titleWeight = heading ? 3 : 10;
    var total = 0;
    for (var i = 0; i < tokens.length; i++) {
      var t = tokens[i];
      var best = Math.max(fieldScore(title, t, titleWeight), fieldScore(heading, t, 6),
        fieldScore(description, t, 2), fieldScore(content, t, 1));
      if (!best) return 0;
      total += best;
    }
    return total;
  }

  // Every record matching all tokens, best first (stable on ties).
  function search(records, query, cjk) {
    var tokens = tokenize(query, cjk);
    if (!tokens.length) return [];
    var hits = [];
    records.forEach(function (record, index) {
      var score = scoreRecord(record, tokens);
      if (score) hits.push({ record: record, score: score, index: index });
    });
    hits.sort(function (a, b) { return b.score - a.score || a.index - b.index; });
    return hits.map(function (h) { return h.record; });
  }

  // A window of `text` around the first token match, as [string, isMatch]
  // pieces. Pure data: the DOM side turns them into text nodes and <mark>s.
  function excerpt(text, tokens, length) {
    text = typeof text === "string" ? text : "";
    length = length || EXCERPT_LENGTH;
    var low = text.toLowerCase();
    var first = -1;
    tokens.forEach(function (t) {
      var i = low.indexOf(t);
      if (i >= 0 && (first < 0 || i < first)) first = i;
    });
    var start = Math.max(0, first < 0 ? 0 : first - Math.floor(length / 4));
    var end = Math.min(text.length, start + length);
    var piece = text.slice(start, end);
    var pieces = highlight(piece, tokens);
    if (start > 0) pieces.unshift(["…", false]);
    if (end < text.length) pieces.push(["…", false]);
    return pieces;
  }

  // Split `text` into [string, isMatch] pieces at token matches.
  // ponytail: index math assumes toLowerCase() keeps string length, which
  // a handful of characters (U+0130) break; it only shifts the <mark>.
  function highlight(text, tokens) {
    var low = text.toLowerCase();
    var marks = [];
    tokens.forEach(function (t) {
      var from = 0, i;
      while (t && (i = low.indexOf(t, from)) >= 0) {
        marks.push([i, i + t.length]);
        from = i + t.length;
      }
    });
    marks.sort(function (a, b) { return a[0] - b[0]; });
    var pieces = [], pos = 0;
    marks.forEach(function (m) {
      if (m[1] <= pos) return;
      var s = Math.max(m[0], pos);
      if (s > pos) pieces.push([text.slice(pos, s), false]);
      pieces.push([text.slice(s, m[1]), true]);
      pos = m[1];
    });
    if (pos < text.length) pieces.push([text.slice(pos), false]);
    return pieces;
  }

  // The index URL only when it resolves to this site's own origin over
  // http(s): rejects `javascript:`/`data:` and any other scheme, and
  // protocol-relative or backslash tricks that leave the origin.
  function safeUrl(url, origin) {
    if (typeof url !== "string" || !url || /[\u0000-\u001f]/.test(url)) return null;
    try {
      var u = new URL(url, origin);
      if ((u.protocol !== "http:" && u.protocol !== "https:") || u.origin !== origin) return null;
      return u.pathname + u.search + u.hash;
    } catch (e) {
      return null;
    }
  }

  // True when `record` carries `value` for `facet` (a string or a list).
  function hasFacet(record, facet, value) {
    var v = record[facet];
    return Array.isArray(v) ? v.indexOf(value) >= 0 : v === value;
  }

  var core = { untokenize: untokenize, tokenize: tokenize, search: search, excerpt: excerpt, highlight: highlight, safeUrl: safeUrl, hasFacet: hasFacet };
  if (typeof document === "undefined") {
    if (typeof module !== "undefined") module.exports = core;
    return;
  }

  var script = document.currentScript || document.querySelector("script[data-hwaro-search-config]");
  var config = {};
  try { config = JSON.parse(script.getAttribute("data-hwaro-search-config")) || {}; } catch (e) { config = {}; }
  var i18n = config.i18n || {};
  var facets = Array.isArray(config.facets) ? config.facets : [];
  var uid = "hwaro-search-" + Math.random().toString(36).slice(2, 8);

  var records = null, loading = null;
  var ui = null, overlay = null, inline = false, lastFocus = null;
  var results = [], active = -1, filters = {};

  function el(tag, cls, text) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text != null) e.textContent = text;
    return e;
  }

  function getJson(url) {
    return fetch(url, { credentials: "same-origin" }).then(function (r) {
      if (!r.ok) throw new Error(url + ": " + r.status);
      return r.json();
    });
  }

  // Lazy, once: the language's shards from the manifest, else the single
  // index; multilingual sites keep only the current language's records.
  function load() {
    if (loading) return loading;
    var lang = config.lang;
    var fetchAll;
    if (config.manifest) {
      fetchAll = getJson(config.manifest).then(function (m) {
        var shards = (m.shards || []).filter(function (s) {
          return !lang || !s.language || s.language === lang;
        });
        return Promise.all(shards.map(function (s) {
          var url = safeUrl(s.url, location.origin);
          return url ? getJson(url) : [];
        }));
      }).then(function (lists) { return [].concat.apply([], lists); });
    } else {
      fetchAll = getJson(config.index);
    }
    loading = fetchAll.then(function (data) {
      records = (Array.isArray(data) ? data : []).filter(function (r) {
        return r && typeof r === "object" && (!lang || !r.lang || r.lang === lang);
      });
    }).catch(function (err) {
      records = [];
      if (window.console) console.warn("hwaro search:", err);
    }).then(render);
    return loading;
  }

  function build(host) {
    var root = el("div", "hwaro-search");
    var bar = el("div", "hwaro-search-bar");
    var input = el("input", "hwaro-search-input");
    input.type = "search";
    input.autocomplete = "off";
    input.spellcheck = false;
    input.placeholder = i18n.placeholder || "Search";
    input.setAttribute("aria-label", input.placeholder);
    input.setAttribute("role", "combobox");
    input.setAttribute("aria-autocomplete", "list");
    input.setAttribute("aria-expanded", "false");
    input.setAttribute("aria-controls", uid + "-list");
    bar.appendChild(input);
    var close = null;
    if (!host) {
      close = el("button", "hwaro-search-close", "Esc");
      close.type = "button";
      close.setAttribute("aria-label", i18n.close || "Close");
      close.addEventListener("click", hide);
      bar.appendChild(close);
    }
    var chips = el("div", "hwaro-search-facets");
    chips.setAttribute("role", "group");
    chips.hidden = true;
    var status = el("div", "hwaro-search-status");
    status.setAttribute("role", "status");
    status.setAttribute("aria-live", "polite");
    var list = el("ul", "hwaro-search-results");
    list.id = uid + "-list";
    list.setAttribute("role", "listbox");
    list.setAttribute("aria-label", input.placeholder);
    root.appendChild(bar);
    root.appendChild(chips);
    root.appendChild(status);
    root.appendChild(list);
    input.addEventListener("input", function () { filters = {}; render(); });
    input.addEventListener("keydown", onKey);
    input.addEventListener("focus", load);
    return { root: root, input: input, chips: chips, status: status, list: list };
  }

  function mount() {
    if (ui) return;
    var host = document.querySelector("[data-hwaro-search-input]");
    if (host) {
      inline = true;
      ui = build(host);
      ui.root.classList.add("hwaro-search-inline");
      host.appendChild(ui.root);
      return;
    }
    ui = build(null);
    overlay = el("div", "hwaro-search-overlay");
    overlay.hidden = true;
    var dialog = el("div", "hwaro-search-dialog");
    dialog.setAttribute("role", "dialog");
    dialog.setAttribute("aria-modal", "true");
    dialog.setAttribute("aria-label", ui.input.placeholder);
    dialog.appendChild(ui.root);
    overlay.appendChild(dialog);
    overlay.addEventListener("mousedown", function (e) { if (e.target === overlay) hide(); });
    dialog.addEventListener("keydown", trapFocus);
    document.body.appendChild(overlay);
  }

  function open() {
    mount();
    if (!inline) {
      if (!overlay.hidden) return;
      lastFocus = document.activeElement;
      overlay.hidden = false;
      document.documentElement.classList.add("hwaro-search-open");
    }
    ui.input.focus();
    ui.input.select();
    load();
  }

  function hide() {
    if (inline) {
      ui.input.value = "";
      render();
      ui.input.blur();
      return;
    }
    if (!overlay || overlay.hidden) return;
    overlay.hidden = true;
    document.documentElement.classList.remove("hwaro-search-open");
    // preventScroll: a result link to `#heading` on this page must keep its jump.
    if (lastFocus && lastFocus.focus) lastFocus.focus({ preventScroll: true });
  }

  function trapFocus(e) {
    if (e.key === "Escape") { e.preventDefault(); hide(); return; }
    if (e.key !== "Tab") return;
    var nodes = Array.prototype.filter.call(
      overlay.querySelectorAll("input, button"),
      function (n) { return !n.disabled && n.offsetParent !== null; });
    if (!nodes.length) return;
    var first = nodes[0], last = nodes[nodes.length - 1];
    if (e.shiftKey && document.activeElement === first) { last.focus(); e.preventDefault(); }
    else if (!e.shiftKey && document.activeElement === last) { first.focus(); e.preventDefault(); }
  }

  function onKey(e) {
    if (e.key === "ArrowDown" || e.key === "ArrowUp") {
      if (!results.length) return;
      e.preventDefault();
      var n = results.length;
      setActive(e.key === "ArrowDown" ? (active + 1) % n : (active - 1 + n) % n);
    } else if (e.key === "Enter") {
      var link = active >= 0 && ui.list.children[active] && ui.list.children[active].querySelector("a");
      if (link) { e.preventDefault(); link.click(); }
    } else if (e.key === "Escape") {
      e.preventDefault();
      hide();
    }
  }

  function setActive(i) {
    var items = ui.list.children;
    if (items[active]) items[active].setAttribute("aria-selected", "false");
    active = i;
    if (items[i]) {
      items[i].setAttribute("aria-selected", "true");
      ui.input.setAttribute("aria-activedescendant", items[i].id);
      items[i].scrollIntoView({ block: "nearest" });
    } else {
      ui.input.removeAttribute("aria-activedescendant");
    }
  }

  function appendPieces(parent, pieces) {
    pieces.forEach(function (p) {
      parent.appendChild(p[1] ? el("mark", null, p[0]) : document.createTextNode(p[0]));
    });
  }

  function renderChips(hits) {
    var box = ui.chips;
    while (box.firstChild) box.removeChild(box.firstChild);
    var any = false;
    facets.forEach(function (facet) {
      var counts = {};
      hits.forEach(function (r) {
        var v = r[facet];
        (Array.isArray(v) ? v : [v]).forEach(function (x) {
          if (typeof x === "string" && x) counts[x] = (counts[x] || 0) + 1;
        });
      });
      Object.keys(counts).sort(function (a, b) { return counts[b] - counts[a] || (a < b ? -1 : 1); })
        .slice(0, MAX_CHIPS).forEach(function (value) {
          any = true;
          var on = filters[facet] === value;
          var chip = el("button", "hwaro-search-chip", value);
          chip.type = "button";
          chip.setAttribute("data-facet", facet);
          chip.setAttribute("aria-pressed", on ? "true" : "false");
          chip.addEventListener("click", function () {
            if (on) delete filters[facet]; else filters[facet] = value;
            render();
            ui.input.focus();
          });
          box.appendChild(chip);
        });
    });
    box.hidden = !any;
  }

  function render() {
    if (!ui) return;
    var query = ui.input.value;
    var list = ui.list;
    while (list.firstChild) list.removeChild(list.firstChild);
    active = -1;
    ui.input.removeAttribute("aria-activedescendant");
    var hits = records && query.trim() ? search(records, query, !!config.cjk) : [];
    renderChips(hits);
    Object.keys(filters).forEach(function (facet) {
      hits = hits.filter(function (r) { return hasFacet(r, facet, filters[facet]); });
    });
    results = [];
    var tokens = tokenize(query, !!config.cjk);
    var show = config.cjk ? untokenize : String;
    hits.forEach(function (r) {
      if (results.length >= MAX_RESULTS) return;
      var url = safeUrl(r.url, location.origin);
      if (!url) return;
      var li = el("li", "hwaro-search-result");
      li.id = uid + "-opt-" + results.length;
      li.setAttribute("role", "option");
      li.setAttribute("aria-selected", "false");
      var a = el("a", "hwaro-search-link");
      a.href = url;
      a.tabIndex = -1;
      a.addEventListener("click", function () { hide(); });
      var title = el("span", "hwaro-search-title");
      appendPieces(title, highlight(show(r.title || url), tokens));
      if (typeof r.heading === "string" && r.heading) {
        title.appendChild(el("span", "hwaro-search-sep", " › "));
        var h = el("span", "hwaro-search-heading");
        appendPieces(h, highlight(show(r.heading), tokens));
        title.appendChild(h);
      }
      a.appendChild(title);
      var text = typeof r.content === "string" && r.content ? r.content : r.description;
      if (typeof text === "string" && text) {
        var ex = el("span", "hwaro-search-excerpt");
        appendPieces(ex, excerpt(show(text), tokens));
        a.appendChild(ex);
      }
      li.appendChild(a);
      list.appendChild(li);
      results.push(r);
    });
    ui.input.setAttribute("aria-expanded", results.length ? "true" : "false");
    var count = results.length;
    var msg = "";
    if (query.trim() && records) {
      msg = count ? (count === 1 ? i18n.results_one || "{count} result" : i18n.results_other || "{count} results").replace("{count}", String(count))
        : i18n.no_results || "No results";
    } else if (query.trim()) {
      msg = "…";
    }
    ui.status.textContent = msg;
  }

  document.addEventListener("keydown", function (e) {
    if ((e.metaKey || e.ctrlKey) && !e.altKey && (e.key === "k" || e.key === "K")) {
      e.preventDefault();
      open();
      return;
    }
    if (e.key !== "/" || e.metaKey || e.ctrlKey || e.altKey) return;
    var t = e.target;
    if (t && (t.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName))) return;
    e.preventDefault();
    open();
  });

  document.addEventListener("click", function (e) {
    var trigger = e.target && e.target.closest && e.target.closest("[data-hwaro-search]");
    if (!trigger) return;
    e.preventDefault();
    open();
  });

  if (document.querySelector("[data-hwaro-search-input]")) {
    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", mount);
    else mount();
  }
})();
